# Generated by Django 4.2.27 on 2025-12-16 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=200, unique=True)),
                ('common_name', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='species/covers/')),
                ('short_desc', models.TextField(blank=True)),
                ('kingdom', models.CharField(blank=True, max_length=80)),
                ('phylum', models.CharField(blank=True, max_length=80)),
                ('class_name', models.CharField(blank=True, max_length=80)),
                ('order', models.CharField(blank=True, max_length=80)),
                ('family', models.CharField(blank=True, max_length=80)),
                ('genus', models.CharField(blank=True, max_length=80)),
                ('ncbi_url', models.URLField(blank=True)),
                ('worms_url', models.URLField(blank=True)),
                ('group', models.CharField(choices=[('best', 'Best'), ('upcoming', 'Upcoming'), ('public', 'Public')], default='best', max_length=30)),
                ('is_public', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='species/resources/')),
                ('file_type', models.CharField(choices=[('fasta', 'FASTA'), ('gff', 'GFF'), ('proteome', 'Proteome'), ('transcriptome', 'Transcriptome'), ('edna', 'eDNA'), ('other', 'Other')], default='other', max_length=30)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='genome.species')),
            ],
        ),
    ]
