# Generated by Django 4.2.27 on 2025-12-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='static_image',
            field=models.CharField(blank=True, help_text='Path under static/, e.g. species/podabacia_crustacea.jpg', max_length=200),
        ),
    ]
