# Generated by Django 4.2.27 on 2025-12-19 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genome', '0002_species_static_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('static_image', models.CharField(help_text='Path under static/, e.g. species/tubastraea_1.jpg', max_length=200)),
                ('caption', models.CharField(blank=True, help_text='Optional description of the image', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='genome.species')),
            ],
        ),
    ]
